// Generated by CoffeeScript 1.7.1
(function() {
  var app, controllers, express, inst, settings;

  settings = require('./settings');

  app = settings.app;

  express = settings.express;

  inst = settings.inst;

  app.configure(function() {
    app.use(express.cookieParser());
    app.use(express.session({
      store: new settings.redisStore({
        host: settings.REDIS_HOST,
        port: settings.REDIS_PORT,
        db: 2,
        pass: ''
      }),
      secret: process.env.IG_SESSION_SECRET || '1asdfkljh32rsadfa34'
    }));
    app.use(express.methodOverride());
    app.use(express.bodyParser());
    app.use(app.router);
    app.use(express["static"](__dirname + '/public/'));
    app.use(express.favicon('public/static/images/favicon.ico'));
    console.log('running on ' + settings.HOSTNAME);
    inst.set('client_id', settings.CLIENT_ID);
    inst.set('client_secret', settings.CLIENT_SECRET);
    return inst.set('redirect_uri', settings.HOSTNAME + '/oauth/callback');
  });

  app.configure('development', function() {
    app.use(express.logger());
    return app.use(express.errorHandler({
      dumpExceptions: true,
      showStack: true
    }));
  });

  app.configure('production', function() {
    return app.use(express.errorHandler());
  });

  controllers = require('./controllers');

}).call(this);
