// Generated by CoffeeScript 1.7.1
(function() {
  var app, fs, helpers, io, jade, pubSubClient, redis, redisClient, settings, subscriptionPattern;

  redis = require('redis');

  fs = require('fs');

  jade = require('jade');

  settings = require('./settings');

  helpers = require('./helpers');

  app = settings.app;

  io = settings.io;

  subscriptionPattern = 'channel:*';

  redisClient = redis.createClient(settings.REDIS_URL);

  pubSubClient = redis.createClient(settings.REDIS_URL);

  pubSubClient.psubscribe(subscriptionPattern);

  pubSubClient.on('pmessage', function(pattern, channel, message) {
    var channelName, data, e, index, media, update;
    helpers.debug('Handling pmessage');
    if (pattern === subscriptionPattern) {
      try {
        data = JSON.parse(message);
        channelName = channel.split(':')[1].replace(/-/g, ' ');
      } catch (_error) {
        e = _error;
        helpers.debug(e);
        return;
      }
      for (index in data) {
        media = data[index];
        media.meta = {};
        media.tag = channelName;
        redisClient.lpush('media:objects:' + channelName, JSON.stringify(media));
      }
      update = {
        type: 'newMedia',
        media: data,
        channelName: channelName
      };
      helpers.debug('emitting message for ' + channelName);
      return io.sockets.emit('newMedia-' + channelName, data);
    }
  });

  io.sockets.on("connection", function(socket) {
    return socket.emit("greet", {
      greeting: "hello"
    });
  });

}).call(this);
